// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pulse_generator_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln5,
        out_r,
        out_r_ap_vld,
        n_reps,
        div_Addr_A,
        div_EN_A,
        div_WEN_A,
        div_Din_A,
        div_Dout_A
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [34:0] mul_ln5;
output  [0:0] out_r;
output   out_r_ap_vld;
input  [31:0] n_reps;
output  [31:0] div_Addr_A;
output   div_EN_A;
output  [3:0] div_WEN_A;
output  [31:0] div_Din_A;
input  [31:0] div_Dout_A;

reg ap_idle;
reg[0:0] out_r;
reg out_r_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln10_fu_130_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln12_fu_141_p2;
reg   [0:0] icmp_ln12_reg_271;
reg   [0:0] icmp_ln12_reg_271_pp0_iter2_reg;
wire   [63:0] zext_ln10_fu_186_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] i_fu_54;
wire   [31:0] select_ln12_fu_152_p3;
wire    ap_loop_init;
reg   [31:0] storemerge4_fu_58;
wire   [31:0] add_ln19_fu_212_p2;
wire   [0:0] icmp_ln13_fu_206_p2;
reg   [3:0] j_fu_62;
wire   [3:0] add_ln10_1_fu_180_p2;
reg   [34:0] indvar_flatten_fu_66;
wire   [34:0] add_ln10_fu_135_p2;
wire    ap_block_pp0_stage0_01001;
reg    div_EN_A_local;
wire   [31:0] div_Addr_A_local;
wire   [31:0] div_Addr_A_orig;
wire   [31:0] add_ln12_fu_146_p2;
wire   [3:0] empty_fu_173_p3;
wire   [31:0] select_ln10_fu_199_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 i_fu_54 = 32'd0;
#0 storemerge4_fu_58 = 32'd0;
#0 j_fu_62 = 4'd0;
#0 indvar_flatten_fu_66 = 35'd0;
#0 ap_done_reg = 1'b0;
end

pulse_generator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_54 <= 32'd0;
        end else if (((icmp_ln10_fu_130_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_54 <= select_ln12_fu_152_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_66 <= 35'd0;
        end else if (((icmp_ln10_fu_130_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_66 <= add_ln10_fu_135_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            j_fu_62 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            j_fu_62 <= add_ln10_1_fu_180_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln13_fu_206_p2 == 1'd1)))) begin
        storemerge4_fu_58 <= 32'd1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln13_fu_206_p2 == 1'd0))) begin
        storemerge4_fu_58 <= add_ln19_fu_212_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln12_reg_271 <= icmp_ln12_fu_141_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln12_reg_271_pp0_iter2_reg <= icmp_ln12_reg_271;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_130_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        div_EN_A_local = 1'b1;
    end else begin
        div_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((icmp_ln13_fu_206_p2 == 1'd1)) begin
            out_r = 1'd1;
        end else if ((icmp_ln13_fu_206_p2 == 1'd0)) begin
            out_r = 1'd0;
        end else begin
            out_r = 'bx;
        end
    end else begin
        out_r = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln13_fu_206_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln13_fu_206_p2 == 1'd0)))) begin
        out_r_ap_vld = 1'b1;
    end else begin
        out_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_1_fu_180_p2 = (j_fu_62 + empty_fu_173_p3);

assign add_ln10_fu_135_p2 = (indvar_flatten_fu_66 + 35'd1);

assign add_ln12_fu_146_p2 = (i_fu_54 + 32'd1);

assign add_ln19_fu_212_p2 = (select_ln10_fu_199_p3 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign div_Addr_A = div_Addr_A_local;

assign div_Addr_A_local = div_Addr_A_orig << 32'd2;

assign div_Addr_A_orig = zext_ln10_fu_186_p1;

assign div_Din_A = 32'd0;

assign div_EN_A = div_EN_A_local;

assign div_WEN_A = 4'd0;

assign empty_fu_173_p3 = ((icmp_ln12_reg_271[0:0] == 1'b1) ? 4'd0 : 4'd1);

assign icmp_ln10_fu_130_p2 = ((indvar_flatten_fu_66 == mul_ln5) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_141_p2 = (($signed(i_fu_54) < $signed(n_reps)) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_206_p2 = ((select_ln10_fu_199_p3 == div_Dout_A) ? 1'b1 : 1'b0);

assign select_ln10_fu_199_p3 = ((icmp_ln12_reg_271_pp0_iter2_reg[0:0] == 1'b1) ? storemerge4_fu_58 : 32'd1);

assign select_ln12_fu_152_p3 = ((icmp_ln12_fu_141_p2[0:0] == 1'b1) ? add_ln12_fu_146_p2 : 32'd1);

assign zext_ln10_fu_186_p1 = add_ln10_1_fu_180_p2;

endmodule //pulse_generator_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2
