// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pulse_generator_pulse_generator,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.392417,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=181,HLS_SYN_LUT=531,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module pulse_generator (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        div_Addr_A,
        div_EN_A,
        div_WEN_A,
        div_Din_A,
        div_Dout_A,
        div_Clk_A,
        div_Rst_A,
        n_reps,
        out_r
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] div_Addr_A;
output   div_EN_A;
output  [3:0] div_WEN_A;
output  [31:0] div_Din_A;
input  [31:0] div_Dout_A;
output   div_Clk_A;
output   div_Rst_A;
input  [31:0] n_reps;
output  [0:0] out_r;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] out_r;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] n_reps_read_reg_112;
wire   [34:0] add_ln5_fu_105_p2;
reg   [34:0] add_ln5_reg_117;
wire    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start;
wire    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done;
wire    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_idle;
wire    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_ready;
wire   [0:0] grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r;
wire    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld;
wire   [31:0] grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Addr_A;
wire    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_EN_A;
wire   [3:0] grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_WEN_A;
wire   [31:0] grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Din_A;
reg    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [0:0] out_r_reg;
wire   [0:0] empty_fu_67_p2;
wire   [30:0] trunc_ln5_fu_63_p1;
wire   [30:0] smax_fu_73_p3;
wire   [33:0] tmp_fu_81_p3;
wire   [31:0] tmp_1_fu_93_p3;
wire   [34:0] zext_ln5_fu_89_p1;
wire   [34:0] zext_ln5_1_fu_101_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg = 1'b0;
end

pulse_generator_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2 grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start),
    .ap_done(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done),
    .ap_idle(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_idle),
    .ap_ready(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_ready),
    .mul_ln5(add_ln5_reg_117),
    .out_r(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r),
    .out_r_ap_vld(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld),
    .n_reps(n_reps_read_reg_112),
    .div_Addr_A(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Addr_A),
    .div_EN_A(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_EN_A),
    .div_WEN_A(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_WEN_A),
    .div_Din_A(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Din_A),
    .div_Dout_A(div_Dout_A)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg <= 1'b1;
        end else if ((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_ready == 1'b1)) begin
            grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln5_reg_117[34 : 1] <= add_ln5_fu_105_p2[34 : 1];
        n_reps_read_reg_112 <= n_reps;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_r_reg <= grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_r = grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r;
    end else begin
        out_r = out_r_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln5_fu_105_p2 = (zext_ln5_fu_89_p1 + zext_ln5_1_fu_101_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign div_Addr_A = grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Addr_A;

assign div_Clk_A = ap_clk;

assign div_Din_A = 32'd0;

assign div_EN_A = grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_EN_A;

assign div_Rst_A = ap_rst;

assign div_WEN_A = 4'd0;

assign empty_fu_67_p2 = (($signed(n_reps) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start = grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg;

assign smax_fu_73_p3 = ((empty_fu_67_p2[0:0] == 1'b1) ? trunc_ln5_fu_63_p1 : 31'd0);

assign tmp_1_fu_93_p3 = {{smax_fu_73_p3}, {1'd0}};

assign tmp_fu_81_p3 = {{smax_fu_73_p3}, {3'd0}};

assign trunc_ln5_fu_63_p1 = n_reps[30:0];

assign zext_ln5_1_fu_101_p1 = tmp_1_fu_93_p3;

assign zext_ln5_fu_89_p1 = tmp_fu_81_p3;

always @ (posedge ap_clk) begin
    add_ln5_reg_117[0] <= 1'b0;
end

endmodule //pulse_generator
