// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="counter_counter,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1530,HLS_SYN_LUT=1859,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module counter (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        data_in_TDATA,
        data_in_TVALID,
        data_in_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] data_in_TDATA;
input   data_in_TVALID;
output   data_in_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] data_out;
wire   [31:0] n_outer;
wire   [31:0] n_inner;
reg   [31:0] n_inner_read_reg_140;
reg   [63:0] data_out_read_reg_145;
wire   [30:0] empty_fu_110_p3;
reg   [30:0] empty_reg_150;
wire   [30:0] smax1_fu_124_p3;
reg   [30:0] smax1_reg_156;
wire    ap_CS_fsm_state2;
wire   [61:0] grp_fu_92_p2;
reg   [61:0] mul_ln3_reg_171;
wire    ap_CS_fsm_state3;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_done;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_idle;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_ready;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWID;
wire   [31:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWUSER;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WVALID;
wire   [31:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WDATA;
wire   [3:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WSTRB;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WLAST;
wire   [0:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WID;
wire   [0:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WUSER;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARID;
wire   [31:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARUSER;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_RREADY;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_BREADY;
wire    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_data_in_TREADY;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
wire    gmem_0_ARREADY;
wire    gmem_0_RVALID;
wire   [31:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg    grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [30:0] grp_fu_92_p0;
wire   [30:0] grp_fu_92_p1;
wire   [0:0] icmp_ln15_fu_104_p2;
wire   [30:0] trunc_ln3_1_fu_100_p1;
wire   [0:0] empty_21_fu_118_p2;
wire   [30:0] trunc_ln3_fu_96_p1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_data_in_U_apdone_blk;
wire   [31:0] data_in_TDATA_int_regslice;
wire    data_in_TVALID_int_regslice;
reg    data_in_TREADY_int_regslice;
wire    regslice_both_data_in_U_ack_in;
wire   [61:0] grp_fu_92_p00;
wire   [61:0] grp_fu_92_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start_reg = 1'b0;
end

counter_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2 grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start),
    .ap_done(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_done),
    .ap_idle(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_idle),
    .ap_ready(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(1'b0),
    .m_axi_gmem_0_ARADDR(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(1'b0),
    .m_axi_gmem_0_RREADY(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(32'd0),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(9'd0),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .data_in_TVALID(data_in_TVALID_int_regslice),
    .n_inner(n_inner_read_reg_140),
    .mul_ln3(mul_ln3_reg_171),
    .data_in_TDATA(data_in_TDATA_int_regslice),
    .data_in_TREADY(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_data_in_TREADY),
    .zext_ln14(empty_reg_150),
    .data_out(data_out_read_reg_145)
);

counter_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .data_out(data_out),
    .n_outer(n_outer),
    .n_inner(n_inner),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

counter_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWADDR),
    .I_CH0_AWLEN(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WDATA),
    .I_CH0_WSTRB(grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WSTRB),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

counter_mul_31ns_31ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_92_p0),
    .din1(grp_fu_92_p1),
    .ce(1'b1),
    .dout(grp_fu_92_p2)
);

counter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_data_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TDATA),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_U_ack_in),
    .data_out(data_in_TDATA_int_regslice),
    .vld_out(data_in_TVALID_int_regslice),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_ready == 1'b1)) begin
            grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_out_read_reg_145 <= data_out;
        empty_reg_150 <= empty_fu_110_p3;
        n_inner_read_reg_140 <= n_inner;
        smax1_reg_156 <= smax1_fu_124_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln3_reg_171 <= grp_fu_92_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        data_in_TREADY_int_regslice = grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_data_in_TREADY;
    end else begin
        data_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_0_AWVALID = grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_AWVALID;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_0_BREADY = grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_BREADY;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_0_WVALID = grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_m_axi_gmem_0_WVALID;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_in_TREADY = regslice_both_data_in_U_ack_in;

assign empty_21_fu_118_p2 = (($signed(n_outer) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_110_p3 = ((icmp_ln15_fu_104_p2[0:0] == 1'b1) ? trunc_ln3_1_fu_100_p1 : 31'd0);

assign grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start = grp_counter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_15_2_fu_80_ap_start_reg;

assign grp_fu_92_p0 = grp_fu_92_p00;

assign grp_fu_92_p00 = smax1_reg_156;

assign grp_fu_92_p1 = grp_fu_92_p10;

assign grp_fu_92_p10 = empty_reg_150;

assign icmp_ln15_fu_104_p2 = (($signed(n_inner) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign smax1_fu_124_p3 = ((empty_21_fu_118_p2[0:0] == 1'b1) ? trunc_ln3_fu_96_p1 : 31'd0);

assign trunc_ln3_1_fu_100_p1 = n_inner[30:0];

assign trunc_ln3_fu_96_p1 = n_outer[30:0];

endmodule //counter
