// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="example_example,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.907000,HLS_SYN_LAT=1002,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=65,HLS_SYN_LUT=238,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module example (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_dout,
        A_empty_n,
        A_read,
        counts_address0,
        counts_ce0,
        counts_we0,
        counts_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] A_dout;
input   A_empty_n;
output   A_read;
output  [3:0] counts_address0;
output   counts_ce0;
output   counts_we0;
output  [15:0] counts_d0;

reg ap_idle;
reg A_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln8_fu_136_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    A_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln135_reg_91;
reg   [0:0] A_read_reg_279;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln8_reg_284;
wire   [0:0] icmp_ln13_fu_207_p2;
reg   [0:0] ap_phi_mux_icmp_ln135_phi_fu_95_p4;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
wire   [63:0] zext_ln8_fu_175_p1;
reg   [9:0] indvar_flatten2_fu_52;
wire   [9:0] add_ln8_1_fu_130_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten2_load;
reg   [3:0] i_fu_56;
wire   [3:0] i_3_fu_167_p3;
reg   [31:0] empty_fu_60;
wire   [31:0] add_ln15_fu_187_p2;
reg   [6:0] inc24_fu_64;
wire   [6:0] select_ln18_fu_199_p3;
reg   [3:0] add_ln86_fu_68;
wire   [3:0] add_ln8_fu_218_p2;
reg    counts_we0_local;
wire   [15:0] trunc_ln21_fu_213_p1;
reg    counts_ce0_local;
wire   [31:0] select_ln8_fu_159_p3;
wire   [31:0] empty_6_fu_180_p3;
wire   [6:0] add_ln18_fu_193_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_95;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indvar_flatten2_fu_52 = 10'd0;
#0 i_fu_56 = 4'd0;
#0 empty_fu_60 = 32'd0;
#0 inc24_fu_64 = 7'd0;
#0 add_ln86_fu_68 = 4'd0;
#0 ap_done_reg = 1'b0;
end

example_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            add_ln86_fu_68 <= 4'd1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add_ln86_fu_68 <= add_ln8_fu_218_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            empty_fu_60 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            empty_fu_60 <= add_ln15_fu_187_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            i_fu_56 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_56 <= i_3_fu_167_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1))) begin
            inc24_fu_64 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            inc24_fu_64 <= select_ln18_fu_199_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_95)) begin
        indvar_flatten2_fu_52 <= add_ln8_1_fu_130_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_read_reg_279 <= A_dout;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        icmp_ln8_reg_284 <= icmp_ln8_fu_136_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln8_reg_284 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln135_reg_91 <= icmp_ln13_fu_207_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_blk_n = A_empty_n;
    end else begin
        A_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_read = 1'b1;
    end else begin
        A_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln8_fu_136_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_icmp_ln135_phi_fu_95_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln135_phi_fu_95_p4 = icmp_ln135_reg_91;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten2_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2_load = indvar_flatten2_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counts_ce0_local = 1'b1;
    end else begin
        counts_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_fu_207_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counts_we0_local = 1'b1;
    end else begin
        counts_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_187_p2 = (select_ln8_fu_159_p3 + empty_6_fu_180_p3);

assign add_ln18_fu_193_p2 = (inc24_fu_64 + 7'd1);

assign add_ln8_1_fu_130_p2 = (ap_sig_allocacmp_indvar_flatten2_load + 10'd1);

assign add_ln8_fu_218_p2 = (i_3_fu_167_p3 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (1'b0 == A_empty_n);
end

always @ (*) begin
    ap_condition_95 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign counts_address0 = zext_ln8_fu_175_p1;

assign counts_ce0 = counts_ce0_local;

assign counts_d0 = trunc_ln21_fu_213_p1;

assign counts_we0 = counts_we0_local;

assign empty_6_fu_180_p3 = ((A_read_reg_279[0:0] == 1'b1) ? 32'd1 : 32'd0);

assign i_3_fu_167_p3 = ((ap_phi_mux_icmp_ln135_phi_fu_95_p4[0:0] == 1'b1) ? add_ln86_fu_68 : i_fu_56);

assign icmp_ln13_fu_207_p2 = ((select_ln18_fu_199_p3 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_136_p2 = ((ap_sig_allocacmp_indvar_flatten2_load == 10'd999) ? 1'b1 : 1'b0);

assign select_ln18_fu_199_p3 = ((ap_phi_mux_icmp_ln135_phi_fu_95_p4[0:0] == 1'b1) ? 7'd1 : add_ln18_fu_193_p2);

assign select_ln8_fu_159_p3 = ((ap_phi_mux_icmp_ln135_phi_fu_95_p4[0:0] == 1'b1) ? 32'd0 : empty_fu_60);

assign trunc_ln21_fu_213_p1 = add_ln15_fu_187_p2[15:0];

assign zext_ln8_fu_175_p1 = i_3_fu_167_p3;

endmodule //example
