[hls]
relative_roots=C:/DAQ-HW/hls/pulse_gen/pulse_generator
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=pulse_generator/VITIS_LOOP_12_2 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=pulse_generator/VITIS_LOOP_12_2  


