// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="blinker_blinker,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.552000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=108,HLS_SYN_LUT=278,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module blinker (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C,
        D,
        s_axi_test_AWVALID,
        s_axi_test_AWREADY,
        s_axi_test_AWADDR,
        s_axi_test_WVALID,
        s_axi_test_WREADY,
        s_axi_test_WDATA,
        s_axi_test_WSTRB,
        s_axi_test_ARVALID,
        s_axi_test_ARREADY,
        s_axi_test_ARADDR,
        s_axi_test_RVALID,
        s_axi_test_RREADY,
        s_axi_test_RDATA,
        s_axi_test_RRESP,
        s_axi_test_BVALID,
        s_axi_test_BREADY,
        s_axi_test_BRESP
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_TEST_DATA_WIDTH = 32;
parameter    C_S_AXI_TEST_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_TEST_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] C;
output  [0:0] D;
input   s_axi_test_AWVALID;
output   s_axi_test_AWREADY;
input  [C_S_AXI_TEST_ADDR_WIDTH - 1:0] s_axi_test_AWADDR;
input   s_axi_test_WVALID;
output   s_axi_test_WREADY;
input  [C_S_AXI_TEST_DATA_WIDTH - 1:0] s_axi_test_WDATA;
input  [C_S_AXI_TEST_WSTRB_WIDTH - 1:0] s_axi_test_WSTRB;
input   s_axi_test_ARVALID;
output   s_axi_test_ARREADY;
input  [C_S_AXI_TEST_ADDR_WIDTH - 1:0] s_axi_test_ARADDR;
output   s_axi_test_RVALID;
input   s_axi_test_RREADY;
output  [C_S_AXI_TEST_DATA_WIDTH - 1:0] s_axi_test_RDATA;
output  [1:0] s_axi_test_RRESP;
output   s_axi_test_BVALID;
input   s_axi_test_BREADY;
output  [1:0] s_axi_test_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] C;
reg[0:0] D;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] A;
wire   [31:0] B;
wire   [0:0] trunc_ln12_fu_74_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln12_fu_68_p2;
wire   [0:0] trunc_ln17_fu_85_p1;
wire   [0:0] icmp_ln17_fu_79_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

blinker_test_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_TEST_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_TEST_DATA_WIDTH ))
test_s_axi_U(
    .AWVALID(s_axi_test_AWVALID),
    .AWREADY(s_axi_test_AWREADY),
    .AWADDR(s_axi_test_AWADDR),
    .WVALID(s_axi_test_WVALID),
    .WREADY(s_axi_test_WREADY),
    .WDATA(s_axi_test_WDATA),
    .WSTRB(s_axi_test_WSTRB),
    .ARVALID(s_axi_test_ARVALID),
    .ARREADY(s_axi_test_ARREADY),
    .ARADDR(s_axi_test_ARADDR),
    .RVALID(s_axi_test_RVALID),
    .RREADY(s_axi_test_RREADY),
    .RDATA(s_axi_test_RDATA),
    .RRESP(s_axi_test_RRESP),
    .BVALID(s_axi_test_BVALID),
    .BREADY(s_axi_test_BREADY),
    .BRESP(s_axi_test_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A(A),
    .B(B)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_68_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        C = trunc_ln12_fu_74_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        C = 1'd0;
    end else begin
        C = 1'd0;
    end
end

always @ (*) begin
    if (((icmp_ln17_fu_79_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        D = trunc_ln17_fu_85_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        D = 1'd0;
    end else begin
        D = 1'd0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln12_fu_68_p2 = (($signed(A) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_79_p2 = (($signed(B) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign trunc_ln12_fu_74_p1 = A[0:0];

assign trunc_ln17_fu_85_p1 = B[0:0];

endmodule //blinker
