-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pulse_generator is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    div_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    div_EN_A : OUT STD_LOGIC;
    div_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    div_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    div_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    div_Clk_A : OUT STD_LOGIC;
    div_Rst_A : OUT STD_LOGIC;
    n_reps : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of pulse_generator is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pulse_generator_pulse_generator,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.392417,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=181,HLS_SYN_LUT=531,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal n_reps_read_reg_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln5_fu_105_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln5_reg_117 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start : STD_LOGIC;
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done : STD_LOGIC;
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_idle : STD_LOGIC;
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_ready : STD_LOGIC;
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld : STD_LOGIC;
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_EN_A : STD_LOGIC;
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal out_r_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_67_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln5_fu_63_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_fu_73_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_81_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_1_fu_93_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln5_fu_89_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal zext_ln5_1_fu_101_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pulse_generator_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mul_ln5 : IN STD_LOGIC_VECTOR (34 downto 0);
        out_r : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_r_ap_vld : OUT STD_LOGIC;
        n_reps : IN STD_LOGIC_VECTOR (31 downto 0);
        div_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        div_EN_A : OUT STD_LOGIC;
        div_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        div_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        div_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52 : component pulse_generator_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start,
        ap_done => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done,
        ap_idle => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_idle,
        ap_ready => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_ready,
        mul_ln5 => add_ln5_reg_117,
        out_r => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r,
        out_r_ap_vld => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld,
        n_reps => n_reps_read_reg_112,
        div_Addr_A => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Addr_A,
        div_EN_A => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_EN_A,
        div_WEN_A => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_WEN_A,
        div_Din_A => grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Din_A,
        div_Dout_A => div_Dout_A);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_ready = ap_const_logic_1)) then 
                    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    add_ln5_reg_117(34 downto 1) <= add_ln5_fu_105_p2(34 downto 1);
                n_reps_read_reg_112 <= n_reps;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                out_r_reg <= grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r;
            end if;
        end if;
    end process;
    add_ln5_reg_117(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln5_fu_105_p2 <= std_logic_vector(unsigned(zext_ln5_fu_89_p1) + unsigned(zext_ln5_1_fu_101_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done)
    begin
        if ((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    div_Addr_A <= grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_Addr_A;
    div_Clk_A <= ap_clk;
    div_Din_A <= ap_const_lv32_0;
    div_EN_A <= grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_div_EN_A;
    div_Rst_A <= ap_rst;
    div_WEN_A <= ap_const_lv4_0;
    empty_fu_67_p2 <= "1" when (signed(n_reps) > signed(ap_const_lv32_0)) else "0";
    grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start <= grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_ap_start_reg;

    out_r_assign_proc : process(grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r, grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld, ap_CS_fsm_state2, out_r_reg)
    begin
        if (((grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_r <= grp_pulse_generator_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_12_2_fu_52_out_r;
        else 
            out_r <= out_r_reg;
        end if; 
    end process;

    smax_fu_73_p3 <= 
        trunc_ln5_fu_63_p1 when (empty_fu_67_p2(0) = '1') else 
        ap_const_lv31_0;
    tmp_1_fu_93_p3 <= (smax_fu_73_p3 & ap_const_lv1_0);
    tmp_fu_81_p3 <= (smax_fu_73_p3 & ap_const_lv3_0);
    trunc_ln5_fu_63_p1 <= n_reps(31 - 1 downto 0);
    zext_ln5_1_fu_101_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_93_p3),35));
    zext_ln5_fu_89_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_81_p3),35));
end behav;
